<?php

class AlbumTableSeeder extends Seeder {
    public function run(){
        // DB::table('albums')->delete();
        // $albums = array(
        //     array('id' => '60',
        //         'name' => '女装',
        //         'parent_id' => '0',
        //         'state' => '0',
        //         'store_id' => '1',
        //         'sort' => '0',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '61',
        //         'name' => '男装',
        //         'parent_id' => '0',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '1',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '62',
        //         'name' => '男鞋',
        //         'parent_id' => '0',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '2',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '63',
        //         'name' => '美容美妆',
        //         'parent_id' => '0',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '4',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '64',
        //         'name' => '箱包',
        //         'parent_id' => '0',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '3',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '65',
        //         'name' => '男包',
        //         'parent_id' => '64',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '1',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '66',
        //         'name' => '单肩包',
        //         'parent_id' => '65',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '0',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '67',
        //         'name' => '挎包',
        //         'parent_id' => '65',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '1',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '68',
        //         'name' => '女包',
        //         'parent_id' => '64',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '0',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '69',
        //         'name' => '单肩包',
        //         'parent_id' => '68',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '1',
        //         'is_show'=>'1',
        //     ),
        //     array('id' => '70',
        //         'name' => '挎包',
        //         'parent_id' => '68',
        //         'state' => '1',
        //         'store_id' => '1',
        //         'sort' => '0',
        //         'is_show'=>'1',
        //     ),
        // );
        // DB::table('albums')->insert( $albums );
    }

}
